### ISSUE TITLE
Implement Keyboard Control

### ISSUE THREAD

**Issue by Skyler827** [Skyler827/PongApp#2]
Implement Keyboard Control over pong paddleboards

**Comment by zariman** [comment]
http://jsfiddle.net/loktar/dMYvG/

Here is a javascript code which adds friction which makes the movement of the paddle more dynamic.

**Comment by zariman** [comment]
We could possibly add acceleration to the movement where the speed of the paddles gets faster the longer an arrow key is held down.

**Comment by Skyler827** [comment]
implemented in 1f270013da162c3131bf10078a3f1b1f591df4d7
